// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6fo6Y_5-bG9PsTXRXrLbjyie364XjkwQ',
    appId: '1:1091955552892:android:cafbd053f093658e334ff9',
    messagingSenderId: '1091955552892',
    projectId: 'health-care-176ad',
    databaseURL: 'https://health-care-176ad-default-rtdb.firebaseio.com',
    storageBucket: 'health-care-176ad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuX2LkDiX6tMI1btUneFNlMZSeJulmaKk',
    appId: '1:1091955552892:ios:337658aa5f3e61c6334ff9',
    messagingSenderId: '1091955552892',
    projectId: 'health-care-176ad',
    databaseURL: 'https://health-care-176ad-default-rtdb.firebaseio.com',
    storageBucket: 'health-care-176ad.appspot.com',
    androidClientId: '1091955552892-0gea9s4vv61b6a8fqjlvp0d39f2a5o5a.apps.googleusercontent.com',
    iosClientId: '1091955552892-hsipguhvvet9v6c58evhneam4gdr0ebf.apps.googleusercontent.com',
    iosBundleId: 'com.example.eccatCar',
  );
}
